### ISSUE TITLE
Can u add Entry / Assets / Categories?

### ISSUE THREAD

**Issue by davidhellmann** [charliedevelopment/craft3-advanced-url-field#1]
💯

**Comment by sbossarte** [comment]
Hello @davidhellmann, we've considered adding this kind of capability, but Advanced URL Field's intent is just to expand upon the native, text-based URL field with a few more validation options.

For this kind of capability, the https://github.com/sebastian-lenz/craft-linkfield plugin, or https://github.com/fruitstudios/linkit when it finally gets updated to Craft 3, may better suit your needs.
